// tooling/gates/loopstub.ts — D-426 (Ω-DEV.2): the falsifier-first loop.
//
// The gap this closes: records NAME falsifiers in their Evidence sections,
// but the record→test-file link is convention only — nothing generates the
// RED stub when a record is ratified, nothing audits that every declared
// named falsifier has an executable file, and nothing stops a scaffold
// regen from clobbering an implemented test. This tool makes the loop
// mechanical:
//
//   scaffold a record (omega:new-decision) → it declares named falsifiers
//   → `omega:loop --stub D-NNN` generates tooling/gates/test/f-<id>.test.ts
//     with one RED test per declared clause (throws "not implemented")
//   → the agent implements until every clause passes (the gate runs them)
//   → `omega:loop --status` audits coverage tree-wide
//
// The stub is deterministic (same record → byte-identical stub) and RED by
// construction (each clause throws). Regenerating over an IMPLEMENTED file
// is refused (LOOP_STUB_OVERWRITE) unless --force — an implemented
// falsifier is evidence, and evidence is never silently clobbered.
//
// Bootstrap note, stated honestly: D-425's own stubs were generated by this
// tool AFTER its module landed, inside the same wave — the first generation
// bootstraps (every constitution's first laws predate their enforcement
// machinery); every record from D-426 on gets its stubs at scaffold time.
// Named falsifiers are ALL-CAPS ("F-GENOME"); the record-local F-1..F-N
// convention (D-423/D-424 era) is deliberately out of scope — two
// conventions, one regex, no conflation.
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseRecord } from "./decisions.ts";
import { extractNamedFalsifiers, resolveFalsifierFile, type FalsifierClause } from "./genome.ts";

export interface StubSpec {
  recordN: number;
  id: string;                  // "F-GENOME"
  clauses: Array<{ clause: number | null; title: string | null }>;
}

/** The named falsifiers a record declares, with clause lines. Pure.
 *  Declarations are CLAUSE LINES ONLY ("- F-XXX.N (title) — …"): a bare id
 *  mentioned in prose is a MENTION, not a declaration — the audit and the
 *  stubs follow declarations, so prose can cite other layers' falsifiers
 *  freely without becoming phantom specs. */
export function falsifiersOfRecord(recordText: string): StubSpec[] {
  const doc = parseRecord(0, "record", recordText);
  const declared = extractNamedFalsifiers(doc.evidenceText);
  const out: StubSpec[] = [];
  for (const [id, clauses] of declared) out.push({ recordN: doc.n, id, clauses });
  return out;
}

/** The stub file path for a named falsifier id ("F-GENOME" → f-genome.test.ts). Pure. */
export function stubPath(id: string): string {
  return `tooling/gates/test/f-${id.replace(/^F-/, "").toLowerCase()}.test.ts`;
}

/** Deterministic stub bytes: one RED test per declared clause. Pure. */
export function stubTemplate(spec: StubSpec): string {
  const clauseName = (c: FalsifierClause) =>
    `F-${spec.id.slice(2)}${c.clause !== null ? `.${c.clause}` : ""}${c.title ? ` (${c.title})` : ""}`;
  const tests = (spec.clauses.length > 0 ? spec.clauses : [{ clause: null, title: null }])
    .map((c) => `  test("${clauseName(c)} — RED until implemented", () => {\n    throw new Error("F-${spec.id.slice(2)} not implemented — stub generated from D-${spec.recordN} by omega:loop (D-426); fill the verdict, keep the id");\n  });`)
    .join("\n\n");
  return `// tooling/gates/test/f-${spec.id.toLowerCase()}.test.ts — the ${spec.id} falsifier.
// Generated from D-${spec.recordN} by \`omega:loop --stub D-${spec.recordN}\` (D-426, Ω-DEV.2).
// RED by construction: every clause throws until implemented. This file IS the
// falsifier — fill in the verdicts, keep the ids, make the gate run them green.
import { describe, test } from "bun:test";

describe("${spec.id} (D-${spec.recordN})", () => {
${tests}
});
`;
}

export interface StubResult { written: string[]; refused: Array<{ path: string; reason: string }> }

/** Generate stubs for one record. Refuses to clobber implemented files
 *  (content differs from the stub template) unless force. */
export function generateStubs(root: string, recordN: number, force = false): StubResult {
  const dir = join(root, "docs/decisions");
  const file = readdirSync(dir).find((f) => /^D-(\d+)-/.test(f) && Number(/^D-(\d+)-/.exec(f)![1]) === recordN);
  if (!file) throw new Error(`refused: no record D-${recordN} in docs/decisions/`);
  const text = readFileSync(join(dir, file), "utf-8");
  const specs = falsifiersOfRecord(text);
  const out: StubResult = { written: [], refused: [] };
  for (const spec of specs) {
    const rel = stubPath(spec.id);
    const abs = join(root, rel);
    const stub = stubTemplate({ ...spec, recordN });
    if (existsSync(abs)) {
      const current = readFileSync(abs, "utf-8");
      if (current === stub) continue; // already the stub — idempotent
      if (!force) {
        out.refused.push({ path: rel, reason: `LOOP_STUB_OVERWRITE: ${rel} exists and is not the stub (implemented falsifiers are evidence — never clobbered; --force to regenerate anyway)` });
        continue;
      }
    }
    mkdirSync(join(root, "tooling/gates/test"), { recursive: true });
    writeFileSync(abs, stub);
    out.written.push(rel);
  }
  return out;
}

export interface LoopAuditRow { recordN: number; id: string; file: string | null; clauses: number }

/** The coverage audit: every named falsifier declared by a record resolves to
 *  a test file that carries the id — through the SHARED resolver (genome.ts),
 *  never a second one. Pure over collected inputs. */
export function auditLoop(records: Array<{ n: number; text: string }>, tests: Array<{ path: string; text: string }>): { ok: boolean; rows: LoopAuditRow[]; missing: LoopAuditRow[] } {
  const rows: LoopAuditRow[] = [];
  for (const r of records) {
    for (const spec of falsifiersOfRecord(r.text)) {
      rows.push({ recordN: r.n, id: spec.id, file: resolveFalsifierFile(spec.id, tests), clauses: spec.clauses.length });
    }
  }
  const missing = rows.filter((r) => r.file === null);
  return { ok: missing.length === 0, rows, missing };
}

/** The live audit over a repo root. */
export function auditLoopRoot(root: string): { ok: boolean; rows: LoopAuditRow[]; missing: LoopAuditRow[] } {
  const dir = join(root, "docs/decisions");
  const records = readdirSync(dir)
    .filter((f) => /^D-\d+-.+\.md$/.test(f))
    .map((f) => ({ n: Number(/^D-(\d+)-/.exec(f)![1]), text: readFileSync(join(dir, f), "utf-8") }));
  const tests = walkTests(root);
  return auditLoop(records, tests);
}

function walkTests(root: string): Array<{ path: string; text: string }> {
  const out: Array<{ path: string; text: string }> = [];
  const skip = new Set(["node_modules", ".git", "build", "dev-vault", ".gen", ".test-tmp"]);
  const rec = (dir: string) => {
    for (const f of readdirSync(dir)) {
      if (skip.has(f)) continue;
      const p = join(dir, f);
      if (statSync(p).isDirectory()) { rec(p); continue; }
      if (!/\.(test\.ts|test\.mjs)$/.test(f)) continue;
      out.push({ path: p.slice(root.length + 1), text: readFileSync(p, "utf-8") });
    }
  };
  rec(root);
  return out.sort((a, b) => (a.path < b.path ? -1 : 1));
}

// ---- CLI (`omega:loop --stub D-NNN [--force]` · `--status`) ----

if (import.meta.main) {
  const ROOT = join(import.meta.dir, "../..");
  try {
    const stubIdx = process.argv.indexOf("--stub");
    if (stubIdx !== -1) {
      const n = Number(process.argv[stubIdx + 1]?.replace(/^D-/i, ""));
      if (!Number.isInteger(n) || n <= 0) throw new Error("refused: --stub needs a D-number (e.g. --stub D-426)");
      const r = generateStubs(ROOT, n, process.argv.includes("--force"));
      if (r.written.length === 0 && r.refused.length === 0) console.log(`no named falsifiers declared in D-${n} — nothing to stub (the record-local F-N convention is out of scope by design)`);
      for (const w of r.written) console.log(`stub: ${w} (RED by construction — implement until green)`);
      for (const x of r.refused) console.error(`refused: ${x.reason}`);
      process.exit(r.refused.length > 0 && r.written.length === 0 ? 1 : 0);
    } else {
      const a = auditLoopRoot(ROOT);
      for (const row of a.rows) console.log(`${row.file ? "✓" : "✗"} ${row.id} (D-${row.recordN}, ${row.clauses} clause${row.clauses === 1 ? "" : "s"}) → ${row.file ?? "NO TEST FILE"}`);
      console.log(a.ok ? "loop coverage: GREEN — every named falsifier resolves to an executable" : `loop coverage: RED — ${a.missing.length} unresolved (LOOP_FALSIFIER_UNRESOLVED)`);
      process.exit(a.ok ? 0 : 1);
    }
  } catch (e) {
    console.error(String(e instanceof Error ? e.message : e));
    process.exit(1);
  }
}
