// Pin the generality fixtures: write sdk/test/fixtures/generality/manifest.json
// with sha256 per fixture (re-runnable; idempotent). Wave 0 / D-405.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = import.meta.dir;
const files = readdirSync(DIR).filter((f) => f.endsWith(".json") && f !== "manifest.json").sort();
const rows: Record<string, string> = {};
for (const f of files) {
  rows[f] = `sha256:${createHash("sha256").update(readFileSync(join(DIR, f))).digest("hex")}`;
}
const out = {
  _note: "Hash-pinned generality fixtures (Wave 0 / D-405). Determinism: regenerate with bun run scripts support — bun tooling/gates/test/... via `bun run` not required; this file is regenerated by `bun run sdk/test/fixtures/generality/pin.ts` (any edit to a fixture must re-pin, and the test verifies every hash).",
  fixtures: rows,
};
writeFileSync(join(DIR, "manifest.json"), JSON.stringify(out, null, 2) + "\n");
console.log(`pinned ${files.length} fixtures`);
